# vim: set ft=yaml.ansible:
---
- name: Common Workstation
  gather_facts: false
  hosts: all

  vars_files:
    - vars/packagegroups.yml
    - vars/configs.yml

  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - min
          - hardware
      tags: [always]

    - name: Optimize DNF configuration
      become: true
      ansible.builtin.blockinfile:
        path: /etc/dnf/dnf.conf
        block: |
          max_parallel_downloads=10
          fastestmirror=True
      when: ansible_distribution == "Fedora"
      tags: [always]

    - name: "Ensure package dependencies are installed"
      become: true
      ansible.builtin.package:
        name: "{{ packagegroup[ansible_distribution] + packagegroup.common }}"
        state: present
      tags: [package]

  roles:
    - { role: hardware, tags: hardware }
    - { role: network, tags: network }
    - { role: bluetooth, tags: bluetooth }
    - { role: audio, tags: audio }
    - { role: gpu, tags: gpu }
    - { role: firewall, tags: firewall }
    - { role: storage, tags: storage }
    - { role: power, tags: power }
    - { role: hyprland, tags: hyprland }
    - { role: terminal, tags: terminal }
    - { role: virtualization, tags: [virtualization, libvirt] }
    - { role: devtools, tags: devtools }
    - { role: neovim, tags: neovim }
    - { role: nerdfonts, tags: nerdfonts }
    - { role: lazygit, tags: lazygit }
    - { role: dotfiles, tags: dotfiles }
    - { role: theming, tags: theming }
    - { role: polkit, tags: polkit }
    - { role: xdg, tags: xdg }
    - { role: sddm, tags: sddm }
    - { role: renode, tags: renode }

  tasks:
    - name: Clone personal git projects
      ansible.builtin.git:
        repo: "{{ 'https://github.com/' if ansible_user_id == 'vagrant' else 'git@github.com:' }}{{ item }}"
        depth: 1
        dest: "{{ ansible_user_dir }}/projects/git/{{ item | basename | replace('.git', '') }}"
        version: "master"
        update: false
      loop:
        - "orjangj/neotest-ctest.git"
        - "orjangj/polar.nvim.git"
      tags: [projects]
