#!/bin/sh

# Vagrant-Libvirt VM Environment Setup Script
#
# Normally this is called as '. ./vm-init-env <distro>' or 'source ./vm-init-env <distro>'
# The <distro> is optional, and will default to 'fedora' unless specified.
#

THIS_SCRIPT="$(pwd)/vm-init-env"
if [ ! -e "$THIS_SCRIPT" ]; then
    echo "Error: $THIS_SCRIPT doesn't exist!" >&2
    echo "Please run this script in vm-init-env's directory." >&2
    exit 1
fi

if [ "$0" = "$THIS_SCRIPT" ]; then
    echo "Error: This script needs to be sourced. Please run as '. $THIS_SCRIPT'" >&2
    exit 1
fi
unset THIS_SCRIPT

export VM_DISTRO="${1:-fedora}"
export VM_URI="qemu:///system"  # Must match uri in Vagrantfile (either system or session)
export VM_ATTACH="${PWD##*/}_${VM_DISTRO}"  # Relies on default libvirt VM naming convention
export VM_ENV="qemu:${VM_ATTACH}"

# TODO: alias or export?
alias vm="${PWD}/vm.sh"

