renode_dependencies:
  Archlinux:
    - mono
    - gtk-sharp-2
    - polkit
    - screen
    - gcc
    - python
    - python-pip
  Fedora:
    - mono-complete
    - polkit
    - gtk2
    - screen
    - gtk-sharp2
    - glibc-devel
    - gcc
    - python3
    - python3-pip
