---
theming_qt_packages:
  Archlinux:
    - kvantum
    - qt5ct
    - qt6ct
  Fedora:
    - kvantum
    - qt5ct
    - qt6ct

theming_sddm_packages:
  Archlinux:
    - sddm-kcm
  Fedora:
    - sddm-breeze
