---
sddm_packages:
  Archlinux:
    - sddm
    - qt6-5compat
    - qt6-declarative
    - qt6-svg
  Fedora:
    - sddm
    - sddm-wayland-generic
    - qt6-qt5compat
    - qt6-qtdeclarative
    - qt6-qtsvg
