# vim: set ft=yaml.ansible:
---
- name: Ensure local fonts directory exists
  ansible.builtin.file:
    state: directory
    mode: "0755"
    path: "{{ ansible_user_dir }}/.local/share/fonts"

- name: Check if nerdfonts are already installed
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.local/share/fonts/HackNerdFont-Regular.ttf"
  register: nerdfonts_installed

- name: Install nerdfonts
  ansible.builtin.unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ nerdfonts_version }}/{{ item }}.zip"
    dest: "{{ ansible_user_dir }}/.local/share/fonts"
    remote_src: true
  loop: "{{ nerdfonts_families }}"
  when: not nerdfonts_installed.stat.exists
  tags: [nerdfonts]
