---
dotfiles_repo: "https://github.com/orjangj/dotfiles.git"
lazygit_version: "v0.59.0"
theming_wallpaper_sources:
  - https://github.com/orjangj/wallpapers
renode_version: "1.16.1"
nerdfonts_version: "v3.4.0"
nerdfonts_families:
  - Hack
  - Noto
  - Ubuntu
  - UbuntuMono
theming_nordzy_cursors_version: "v2.4.0"
theming_nordzy_icon_version: "1.8.7"
