---
- name: Ensure local directories exist
  ansible.builtin.file:
    state: directory
    mode: "0755"
    path: "{{ ansible_user_dir }}/{{ item }}"
  loop:
    - ".themes"
    - ".icons"

- name: Check if themes are already installed
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.themes/Nordic"
  register: themes_installed

- name: Install themes
  ansible.builtin.unarchive:
    src: "{{ item.src }}"
    dest: "{{ ansible_user_dir }}/{{ item.dest }}"
    remote_src: true
  loop:
    - { src: "https://github.com/EliverLara/Nordic/releases/download/{{ nordic_version }}/Nordic.tar.xz", dest: ".themes" }
    - { src: "https://github.com/EliverLara/Nordic/releases/download/{{ nordic_version }}/Nordic-darker.tar.xz", dest: ".themes" }
    - { src: "https://github.com/guillaumeboehm/Nordzy-cursors/releases/download/{{ nordzy_cursors_version }}/Nordzy-cursors.tar.gz", dest: ".icons" }
    - { src: "https://github.com/MolassesLover/Nordzy-icon/releases/download/{{ nordzy_icon_version }}/Nordzy.tar.gz", dest: ".icons" }
  when: not themes_installed.stat.exists
