---
- name: Ensure bash is installed
  become: true
  ansible.builtin.package:
    name:
      - bash
      - bash-completion
    state: present

- name: "Ensure bash is set as default shell for user '{{ terminal_user }}'"
  become: true
  ansible.builtin.user:
    name: "{{ terminal_user }}"
    shell: /bin/bash
