---
- name: Install Neovim from package
  ansible.builtin.include_tasks: package.yml
  when: neovim_install_method == "package"

- name: Install Neovim from source
  ansible.builtin.include_tasks: source.yml
  when: neovim_install_method == "source"
